# Generated by Django 4.2.6 on 2023-10-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cars',
            field=models.ManyToManyField(through='project_first_app.Owning', to='project_first_app.car'),
        ),
    ]
