# Generated by Django 4.2.6 on 2023-10-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_driver_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='id_car_owner',
            new_name='id_driver',
        ),
    ]
