# Generated by Django 4.0.10 on 2024-01-30 04:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    
    dependencies = [
    ]
    
    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profit_percentage', models.FloatField(
                    validators=[django.core.validators.MinValueValidator(0.0),
                                django.core.validators.MaxValueValidator(100.0)]
                )),
                ('fixed_monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.firm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
