# Generated by Django 4.0.10 on 2024-02-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('broker', '0003_remove_broker_created_at_remove_broker_updated_at_and_more'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
