# Generated by Django 4.0.10 on 2024-01-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    
    dependencies = [
        ('manufacturer', '0001_initial'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('unique_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('production_date', models.DateField()),
                ('warranty_period', models.IntegerField()),
                ('measurement_unit', models.CharField(max_length=50)),
                ('manufacturer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_conditions', models.CharField(max_length=200)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
