# Generated by Django 4.0.10 on 2024-02-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0003_remove_product_warranty_period_product_expiry_date_and_more'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateField(),
        ),
    ]
