# Generated by Django 4.0.10 on 2024-02-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_alter_product_production_date'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
