# Generated by Django 4.0.10 on 2024-02-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0006_alter_product_unique_code'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='batch_number',
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
