# Generated by Django 4.0.10 on 2024-02-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productbatch_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='delivery_date',
        ),
    ]
