# Generated by Django 4.0.10 on 2024-01-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    
    dependencies = [
    ]
    
    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('contact_info', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
