# Generated by Django 4.0.10 on 2024-02-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manufacturer', '0003_remove_manufacturer_created_at_and_more'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='firm_name',
            field=models.CharField(default='1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
