# Generated by Django 4.0.10 on 2024-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trade', '0002_alter_trade_product_batch'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='trade',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
