# Generated by Django 4.0.10 on 2024-02-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('broker', '0004_alter_firm_name'),
        ('trade', '0003_alter_trade_end_time'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='trade',
            name='broker',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='broker.broker'
            ),
        ),
        migrations.AlterField(
            model_name='trade',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
