# Generated by Django 5.0 on 2023-12-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tours', '0002_booking'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
