# Generated by Django 5.0 on 2024-01-04 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tours', '0005_tourimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'tour')},
        ),
    ]
