site_name: Документация

theme:
  name: material

nav:
  - Home: index.md
  - lr_1:
      - Task_1: 'lr_1/task_1.md'
      - Task_2: 'lr_1/task_2.md'
      - Task_3: 'lr_1/task_3.md'
      - Task_4: 'lr_1/task_4.md'
      - Task_5: 'lr_1/task_5.md'
  - lr_2:
      - Users: 'lr_2/users.md'
      - Tours: 'lr_2/tours.md'
      - Common: 'lr_2/common.md'
  - lr_3:
      - lr_3.1:
          - Prac_1: 'lr_3/lr_3_1/prac_1.md'
          - Prac_2: 'lr_3/lr_3_1/prac_2.md'
          - Prac_3: 'lr_3/lr_3_1/prac_3.md'
      - lr_3.2:
          - Broker: 'lr_3/lr_3_2/broker.md'
          - Firm: 'lr_3/lr_3_2/firm.md'
          - Manufacturer: 'lr_3/lr_3_2/manufacturer.md'
          - Product: 'lr_3/lr_3_2/product.md'
          - Trade: 'lr_3/lr_3_2/trade.md'
  - lr_4:
      - Api (Axios): 'lr_4/store.md'
      - Router: 'lr_4/router.md'
      - Store (Vuex): 'lr_4/store.md'
      - Views:
          - Login: 'lr_4/views/login.md'
          - Register: 'lr_4/views/register.md'
          - Profile: 'lr_4/views/profile.md'
          - Broker: 'lr_4/views/broker.md'
          - Manufacturer: 'lr_4/views/manufacturer.md'
          - Trades: 'lr_4/views/trades.md'
          - TradeDetail: 'lr_4/views/trade_detail.md'
          - Products: 'lr_4/views/products.md'
          - ProductDetail: 'lr_4/views/product_detail.md'
