# Generated by Django 4.0.10 on 2024-01-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_remove_user_confirmation_code'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                verbose_name='active'
            ),
        ),
    ]
